package com.example.polisapp.dto

enum class ServerErrorEnum {
    OK,
    UNKNOWN_ERROR,
    TEACHER_MISSING,
    COURSE_MISSING,
    COURSE_NOT_FOUND,
    TEACHER_NOT_FOUND,
    STUDENT_NOT_FOUND,
    FILTER_MISSING,
    STUDENT_MISSING,
    DELETE_COURSE_NOT_ALLOWED,
    DELETE_TEACHER_NOT_ALLOWED,
    DELETE_STUDENT_NOT_ALLOWED
}